# training
conf_id: BeeAnts_plain_061521
algorithm: PlainResNet
num_epochs: 2
log_interval: 10
parallel: 0

# data
dataset_root: ./supp/bee_ants
dataset_name: BeeAnts
num_classes: 2
batch_size: 64
num_workers: 4

# model
model_name: PlainResNetClassifier
num_layers: 18
weights_init: ImageNet

# optim
## feature
lr_feature: 0.01
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## lr_scheduler
step_size: 3
gamma: 0.1
